# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planner_msgs/generate_start_goal_configRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import planner_msgs.msg

class generate_start_goal_configRequest(genpy.Message):
  _md5sum = "79a916826efddd8cc7004329adcb7230"
  _type = "planner_msgs/generate_start_goal_configRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
#Start EE pose
float64[] start_ee_pose
int32[] constraint_vec_start_pose

#Goal EE pose
float64[] goal_ee_pose
int32[] constraint_vec_goal_pose

#Permitted displacement of EE w.r.t target frame
array2d_double target_coordinate_dev

#Flag to show config generation in rviz
bool show_motion


================================================================================
MSG: planner_msgs/array2d_double
array1d_double[] array2d_double
================================================================================
MSG: planner_msgs/array1d_double
float64[] array1d_double"""
  __slots__ = ['start_ee_pose','constraint_vec_start_pose','goal_ee_pose','constraint_vec_goal_pose','target_coordinate_dev','show_motion']
  _slot_types = ['float64[]','int32[]','float64[]','int32[]','planner_msgs/array2d_double','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       start_ee_pose,constraint_vec_start_pose,goal_ee_pose,constraint_vec_goal_pose,target_coordinate_dev,show_motion

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(generate_start_goal_configRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.start_ee_pose is None:
        self.start_ee_pose = []
      if self.constraint_vec_start_pose is None:
        self.constraint_vec_start_pose = []
      if self.goal_ee_pose is None:
        self.goal_ee_pose = []
      if self.constraint_vec_goal_pose is None:
        self.constraint_vec_goal_pose = []
      if self.target_coordinate_dev is None:
        self.target_coordinate_dev = planner_msgs.msg.array2d_double()
      if self.show_motion is None:
        self.show_motion = False
    else:
      self.start_ee_pose = []
      self.constraint_vec_start_pose = []
      self.goal_ee_pose = []
      self.constraint_vec_goal_pose = []
      self.target_coordinate_dev = planner_msgs.msg.array2d_double()
      self.show_motion = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.start_ee_pose)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.start_ee_pose))
      length = len(self.constraint_vec_start_pose)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.constraint_vec_start_pose))
      length = len(self.goal_ee_pose)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.goal_ee_pose))
      length = len(self.constraint_vec_goal_pose)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.constraint_vec_goal_pose))
      length = len(self.target_coordinate_dev.array2d_double)
      buff.write(_struct_I.pack(length))
      for val1 in self.target_coordinate_dev.array2d_double:
        length = len(val1.array1d_double)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.Struct(pattern).pack(*val1.array1d_double))
      _x = self.show_motion
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.target_coordinate_dev is None:
        self.target_coordinate_dev = planner_msgs.msg.array2d_double()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.start_ee_pose = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.constraint_vec_start_pose = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.goal_ee_pose = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.constraint_vec_goal_pose = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.target_coordinate_dev.array2d_double = []
      for i in range(0, length):
        val1 = planner_msgs.msg.array1d_double()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.array1d_double = s.unpack(str[start:end])
        self.target_coordinate_dev.array2d_double.append(val1)
      start = end
      end += 1
      (self.show_motion,) = _get_struct_B().unpack(str[start:end])
      self.show_motion = bool(self.show_motion)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.start_ee_pose)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.start_ee_pose.tostring())
      length = len(self.constraint_vec_start_pose)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.constraint_vec_start_pose.tostring())
      length = len(self.goal_ee_pose)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.goal_ee_pose.tostring())
      length = len(self.constraint_vec_goal_pose)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.constraint_vec_goal_pose.tostring())
      length = len(self.target_coordinate_dev.array2d_double)
      buff.write(_struct_I.pack(length))
      for val1 in self.target_coordinate_dev.array2d_double:
        length = len(val1.array1d_double)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.array1d_double.tostring())
      _x = self.show_motion
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.target_coordinate_dev is None:
        self.target_coordinate_dev = planner_msgs.msg.array2d_double()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.start_ee_pose = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.constraint_vec_start_pose = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.goal_ee_pose = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.constraint_vec_goal_pose = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.target_coordinate_dev.array2d_double = []
      for i in range(0, length):
        val1 = planner_msgs.msg.array1d_double()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.array1d_double = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        self.target_coordinate_dev.array2d_double.append(val1)
      start = end
      end += 1
      (self.show_motion,) = _get_struct_B().unpack(str[start:end])
      self.show_motion = bool(self.show_motion)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planner_msgs/generate_start_goal_configResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class generate_start_goal_configResponse(genpy.Message):
  _md5sum = "b054f150db038bf449f81cab30f2cf52"
  _type = "planner_msgs/generate_start_goal_configResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
#Start and Goal Config
float64[] start_conf
float64[] goal_conf

#Result of Start and Goal Config Generation
bool success
"""
  __slots__ = ['start_conf','goal_conf','success']
  _slot_types = ['float64[]','float64[]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       start_conf,goal_conf,success

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(generate_start_goal_configResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.start_conf is None:
        self.start_conf = []
      if self.goal_conf is None:
        self.goal_conf = []
      if self.success is None:
        self.success = False
    else:
      self.start_conf = []
      self.goal_conf = []
      self.success = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.start_conf)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.start_conf))
      length = len(self.goal_conf)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.goal_conf))
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.start_conf = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.goal_conf = s.unpack(str[start:end])
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.start_conf)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.start_conf.tostring())
      length = len(self.goal_conf)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.goal_conf.tostring())
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.start_conf = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.goal_conf = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class generate_start_goal_config(object):
  _type          = 'planner_msgs/generate_start_goal_config'
  _md5sum = '016b486bf23e79f4112223da75806f26'
  _request_class  = generate_start_goal_configRequest
  _response_class = generate_start_goal_configResponse
