# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planner_msgs/array2d_double.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import planner_msgs.msg

class array2d_double(genpy.Message):
  _md5sum = "c0e71cb94ac024b6a7159492ec303e32"
  _type = "planner_msgs/array2d_double"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """array1d_double[] array2d_double
================================================================================
MSG: planner_msgs/array1d_double
float64[] array1d_double"""
  __slots__ = ['array2d_double']
  _slot_types = ['planner_msgs/array1d_double[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       array2d_double

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(array2d_double, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.array2d_double is None:
        self.array2d_double = []
    else:
      self.array2d_double = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.array2d_double)
      buff.write(_struct_I.pack(length))
      for val1 in self.array2d_double:
        length = len(val1.array1d_double)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.Struct(pattern).pack(*val1.array1d_double))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.array2d_double is None:
        self.array2d_double = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.array2d_double = []
      for i in range(0, length):
        val1 = planner_msgs.msg.array1d_double()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.array1d_double = s.unpack(str[start:end])
        self.array2d_double.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.array2d_double)
      buff.write(_struct_I.pack(length))
      for val1 in self.array2d_double:
        length = len(val1.array1d_double)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.array1d_double.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.array2d_double is None:
        self.array2d_double = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.array2d_double = []
      for i in range(0, length):
        val1 = planner_msgs.msg.array1d_double()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.array1d_double = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        self.array2d_double.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
