// Generated by gencpp from file planner_msgs/planning_scene_info.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNING_SCENE_INFO_H
#define PLANNER_MSGS_MESSAGE_PLANNING_SCENE_INFO_H

#include <ros/service_traits.h>


#include <planner_msgs/planning_scene_infoRequest.h>
#include <planner_msgs/planning_scene_infoResponse.h>


namespace planner_msgs
{

struct planning_scene_info
{

typedef planning_scene_infoRequest Request;
typedef planning_scene_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planning_scene_info
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::planning_scene_info > {
  static const char* value()
  {
    return "0f90a5fd7094d6c5f8a02858a00e3072";
  }

  static const char* value(const ::planner_msgs::planning_scene_info&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::planning_scene_info > {
  static const char* value()
  {
    return "planner_msgs/planning_scene_info";
  }

  static const char* value(const ::planner_msgs::planning_scene_info&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::planning_scene_infoRequest> should match
// service_traits::MD5Sum< ::planner_msgs::planning_scene_info >
template<>
struct MD5Sum< ::planner_msgs::planning_scene_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planning_scene_info >::value();
  }
  static const char* value(const ::planner_msgs::planning_scene_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planning_scene_infoRequest> should match
// service_traits::DataType< ::planner_msgs::planning_scene_info >
template<>
struct DataType< ::planner_msgs::planning_scene_infoRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planning_scene_info >::value();
  }
  static const char* value(const ::planner_msgs::planning_scene_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::planning_scene_infoResponse> should match
// service_traits::MD5Sum< ::planner_msgs::planning_scene_info >
template<>
struct MD5Sum< ::planner_msgs::planning_scene_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planning_scene_info >::value();
  }
  static const char* value(const ::planner_msgs::planning_scene_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planning_scene_infoResponse> should match
// service_traits::DataType< ::planner_msgs::planning_scene_info >
template<>
struct DataType< ::planner_msgs::planning_scene_infoResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planning_scene_info >::value();
  }
  static const char* value(const ::planner_msgs::planning_scene_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNING_SCENE_INFO_H
