// Generated by gencpp from file planner_msgs/reset_planner_to_default.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_RESET_PLANNER_TO_DEFAULT_H
#define PLANNER_MSGS_MESSAGE_RESET_PLANNER_TO_DEFAULT_H

#include <ros/service_traits.h>


#include <planner_msgs/reset_planner_to_defaultRequest.h>
#include <planner_msgs/reset_planner_to_defaultResponse.h>


namespace planner_msgs
{

struct reset_planner_to_default
{

typedef reset_planner_to_defaultRequest Request;
typedef reset_planner_to_defaultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset_planner_to_default
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::reset_planner_to_default > {
  static const char* value()
  {
    return "0667a9bbb8555a2127e81724eb62d266";
  }

  static const char* value(const ::planner_msgs::reset_planner_to_default&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::reset_planner_to_default > {
  static const char* value()
  {
    return "planner_msgs/reset_planner_to_default";
  }

  static const char* value(const ::planner_msgs::reset_planner_to_default&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::reset_planner_to_defaultRequest> should match
// service_traits::MD5Sum< ::planner_msgs::reset_planner_to_default >
template<>
struct MD5Sum< ::planner_msgs::reset_planner_to_defaultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::reset_planner_to_default >::value();
  }
  static const char* value(const ::planner_msgs::reset_planner_to_defaultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::reset_planner_to_defaultRequest> should match
// service_traits::DataType< ::planner_msgs::reset_planner_to_default >
template<>
struct DataType< ::planner_msgs::reset_planner_to_defaultRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::reset_planner_to_default >::value();
  }
  static const char* value(const ::planner_msgs::reset_planner_to_defaultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::reset_planner_to_defaultResponse> should match
// service_traits::MD5Sum< ::planner_msgs::reset_planner_to_default >
template<>
struct MD5Sum< ::planner_msgs::reset_planner_to_defaultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::reset_planner_to_default >::value();
  }
  static const char* value(const ::planner_msgs::reset_planner_to_defaultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::reset_planner_to_defaultResponse> should match
// service_traits::DataType< ::planner_msgs::reset_planner_to_default >
template<>
struct DataType< ::planner_msgs::reset_planner_to_defaultResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::reset_planner_to_default >::value();
  }
  static const char* value(const ::planner_msgs::reset_planner_to_defaultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_RESET_PLANNER_TO_DEFAULT_H
