// Generated by gencpp from file planner_msgs/run_planner_configs.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_RUN_PLANNER_CONFIGS_H
#define PLANNER_MSGS_MESSAGE_RUN_PLANNER_CONFIGS_H

#include <ros/service_traits.h>


#include <planner_msgs/run_planner_configsRequest.h>
#include <planner_msgs/run_planner_configsResponse.h>


namespace planner_msgs
{

struct run_planner_configs
{

typedef run_planner_configsRequest Request;
typedef run_planner_configsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct run_planner_configs
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::run_planner_configs > {
  static const char* value()
  {
    return "8ca5afb164ebfb318e4cc0e72e99b251";
  }

  static const char* value(const ::planner_msgs::run_planner_configs&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::run_planner_configs > {
  static const char* value()
  {
    return "planner_msgs/run_planner_configs";
  }

  static const char* value(const ::planner_msgs::run_planner_configs&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::run_planner_configsRequest> should match
// service_traits::MD5Sum< ::planner_msgs::run_planner_configs >
template<>
struct MD5Sum< ::planner_msgs::run_planner_configsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::run_planner_configs >::value();
  }
  static const char* value(const ::planner_msgs::run_planner_configsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::run_planner_configsRequest> should match
// service_traits::DataType< ::planner_msgs::run_planner_configs >
template<>
struct DataType< ::planner_msgs::run_planner_configsRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::run_planner_configs >::value();
  }
  static const char* value(const ::planner_msgs::run_planner_configsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::run_planner_configsResponse> should match
// service_traits::MD5Sum< ::planner_msgs::run_planner_configs >
template<>
struct MD5Sum< ::planner_msgs::run_planner_configsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::run_planner_configs >::value();
  }
  static const char* value(const ::planner_msgs::run_planner_configsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::run_planner_configsResponse> should match
// service_traits::DataType< ::planner_msgs::run_planner_configs >
template<>
struct DataType< ::planner_msgs::run_planner_configsResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::run_planner_configs >::value();
  }
  static const char* value(const ::planner_msgs::run_planner_configsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_RUN_PLANNER_CONFIGS_H
