// Generated by gencpp from file planner_msgs/set_edge_costs.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_SET_EDGE_COSTS_H
#define PLANNER_MSGS_MESSAGE_SET_EDGE_COSTS_H

#include <ros/service_traits.h>


#include <planner_msgs/set_edge_costsRequest.h>
#include <planner_msgs/set_edge_costsResponse.h>


namespace planner_msgs
{

struct set_edge_costs
{

typedef set_edge_costsRequest Request;
typedef set_edge_costsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_edge_costs
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::set_edge_costs > {
  static const char* value()
  {
    return "3cebc05ddbc84f67732803850c09e6e4";
  }

  static const char* value(const ::planner_msgs::set_edge_costs&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::set_edge_costs > {
  static const char* value()
  {
    return "planner_msgs/set_edge_costs";
  }

  static const char* value(const ::planner_msgs::set_edge_costs&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::set_edge_costsRequest> should match
// service_traits::MD5Sum< ::planner_msgs::set_edge_costs >
template<>
struct MD5Sum< ::planner_msgs::set_edge_costsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::set_edge_costs >::value();
  }
  static const char* value(const ::planner_msgs::set_edge_costsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::set_edge_costsRequest> should match
// service_traits::DataType< ::planner_msgs::set_edge_costs >
template<>
struct DataType< ::planner_msgs::set_edge_costsRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::set_edge_costs >::value();
  }
  static const char* value(const ::planner_msgs::set_edge_costsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::set_edge_costsResponse> should match
// service_traits::MD5Sum< ::planner_msgs::set_edge_costs >
template<>
struct MD5Sum< ::planner_msgs::set_edge_costsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::set_edge_costs >::value();
  }
  static const char* value(const ::planner_msgs::set_edge_costsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::set_edge_costsResponse> should match
// service_traits::DataType< ::planner_msgs::set_edge_costs >
template<>
struct DataType< ::planner_msgs::set_edge_costsResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::set_edge_costs >::value();
  }
  static const char* value(const ::planner_msgs::set_edge_costsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_SET_EDGE_COSTS_H
