(cl:defpackage execution_msgs-srv
  (:use )
  (:export
   "EXECUTE_TRAJECTORY_ROBOT"
   "<EXECUTE_TRAJECTORY_ROBOT-REQUEST>"
   "EXECUTE_TRAJECTORY_ROBOT-REQUEST"
   "<EXECUTE_TRAJECTORY_ROBOT-RESPONSE>"
   "EXECUTE_TRAJECTORY_ROBOT-RESPONSE"
   "EXECUTE_TRAJECTORY_RVIZ"
   "<EXECUTE_TRAJECTORY_RVIZ-REQUEST>"
   "EXECUTE_TRAJECTORY_RVIZ-REQUEST"
   "<EXECUTE_TRAJECTORY_RVIZ-RESPONSE>"
   "EXECUTE_TRAJECTORY_RVIZ-RESPONSE"
  ))

